# Generated by Django 4.2.18 on 2025-05-24 20:05

import appWedding.models
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='バンド名')),
                ('imageURL', models.URLField(verbose_name='画像リンク')),
                ('iconURL', models.URLField(verbose_name='アイコンリンク')),
                ('twitterURL', models.URLField(blank=True, null=True, verbose_name='ツイッターリンク')),
                ('youtubeURL', models.URLField(blank=True, null=True, verbose_name='YouTubeリンク')),
                ('applemusicURL', models.URLField(blank=True, null=True, verbose_name='AppleMusicリンク')),
                ('spotifyURL', models.URLField(blank=True, null=True, verbose_name='Spotifyリンク')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='ギャラリー')),
            ],
        ),
        migrations.CreateModel(
            name='EntryForm',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=True, verbose_name='admin status')),
                ('attendance', models.BooleanField(default=True, verbose_name='出欠')),
                ('nameFamily', models.CharField(default='', max_length=10, verbose_name='名字')),
                ('nameFirst', models.CharField(default='', max_length=10, verbose_name='名前')),
                ('nameHFamily', models.CharField(default='', max_length=10, verbose_name='名字(ひらがな)')),
                ('nameHFirst', models.CharField(default='', max_length=10, verbose_name='名前(ひらがな)')),
                ('telNumber', models.CharField(default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="電話番号は次のように入力してください。: '09012345678' ※半角英数字、最大15桁", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='メールアドレス')),
                ('postalCode', models.CharField(default='', max_length=7, validators=[django.core.validators.RegexValidator(message="郵便番号は次のように入力してください。: '1234567' ※半角英数字、最大7桁", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('prefecture', models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], default='岡山県', max_length=4, verbose_name='都道府県')),
                ('city', models.CharField(default='', max_length=50, verbose_name='市区町村')),
                ('streetAddress', models.CharField(default='', max_length=50, verbose_name='番地')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='建物名・号室')),
                ('allergy', models.TextField(blank=True, null=True, verbose_name='アレルギー等')),
                ('bus', models.BooleanField(default=False, verbose_name='送迎バス')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'EntryForm',
            },
            managers=[
                ('objects', appWedding.models.UserManager()),
            ],
        ),
    ]
